name: PR to inform @quill-icons update

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_FULL_NAME: ${{ github.repository }}
  REPO_NAME: ${{ github.event.repository.name }}
  pr_title: '[Quill-Icons] üóÇÔ∏è New version available!'
  pr_body:
    'This pull request was automatically created since a new version of [**@quill-icons**](https://github.com/deriv-com/quill-icons) is available.
    Please merge this PR if everything looks good, so that @quill-icons-park can deploy the latest build to https://quill-icons-park.pages.dev/.
    [Generated on $(date)]'
  pr_label: 'dependencies'

jobs:
  Create-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{env.REPO_FULL_NAME}}
          token: ${{env.GH_TOKEN}}
          path: ${{env.REPO_NAME}}

      - name: Set up Git identity
        run: |
          git config --global user.email "quill-icons-no-reply@deriv.com"
          git config --global user.name "Quill Icons"

      - name: Commit to quill-icons-update branch
        if: success()
        run: |
          cd "${{env.REPO_NAME}}"
          git checkout -b quill-icons-update
          git pull origin master
          npm version patch -m "build: üöÄ %s installs latest quill icons"
          git push --set-upstream -f origin quill-icons-update

      - name: Create Pull Request
        if: success()
        run: |
          cd "${{env.REPO_NAME}}"
          gh pr create --base master --head quill-icons-update --title "${{env.pr_title}}" --body "${{env.pr_body}}" --label "${{env.pr_label}}"
